# Semantic versioning, changelog and disclaimer generation
semver:
    extends: .install
    stage: validate
    script:
        # Make lerna work in CI
        - ./devops/scripts/lerna-ready-ci.sh
        # Skip tags because they already should include the generated CHANGELOG.md
        - '[ ! "$CI_BUILD_TAG" ] && yarn lerna version --yes --no-push --no-git-tag-version --allow-branch "$CI_COMMIT_REF_NAME" --loglevel silly'
    artifacts:
        name: semver
        paths:
            - package.json
            - plugins/*/package.json
            - plugins/*/CHANGELOG.md
            - plugins/*/src/index.php
            - plugins/*/LICENSE_3RD_PARTY*
            - packages/*/package.json
            - packages/*/CHANGELOG.md
            - packages/*/LICENSE_3RD_PARTY*
            - yarn.lock

# Validate licenses for yarn packages
.yarn licenses:
    extends: .install
    stage: validate
    script:
        - cd $JOB_PACKAGE_FOLDER/$JOB_PACKAGE_NAME
        - yarn grunt yarn:license:check

# Validate licenses for composer packages
.composer licenses:
    extends: .install
    stage: validate
    script:
        - cd $JOB_PACKAGE_FOLDER/$JOB_PACKAGE_NAME
        - yarn grunt composer:license:check
